# Generated by Django 6.0.6 on 2026-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
    ]
